#!/bin/sh

# arch-tag: 36b2efee-c150-4a9b-af28-8fe7266a5379

this_dir=$(cd $(dirname $0) && pwd)

if test -z "$GUILE_LOAD_PATH"; then
  export GUILE_LOAD_PATH=$this_dir/src
else
  export GUILE_LOAD_PATH=$this_dir/src:$GUILE_LOAD_PATH
fi
# really should be the builddir...
if test -z "$GUILE_LOAD_COMPILED_PATH"; then
  export GUILE_LOAD_COMPILED_PATH=$this_dir/src
else
  export GUILE_LOAD_COMPILED_PATH=$this_dir/src:$GUILE_LOAD_COMPILED_PATH
fi

exec "$@"

